name: seq-tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.6
  - bioconda::samtools=1.15.1
  - pip
  - pip3:
    - -r requirements.txt
    - -r requirements-test.txt
    - .
