name: seq-tools-0.1.0
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.6
  - bioconda::samtools=1.9
  - bioconda::picard=2.22.4
  - pip
    - -r file:requirements.txt
    - .