name: seq-tools-1.0.1
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.6
  - bioconda::samtools=1.10
  - pip
  - pip:
    - -r file:requirements.txt
    - -r file:requirements-test.txt
    - .
